### ISSUE TITLE
Add delta trending endpoints

### ISSUE THREAD

**Issue by broskoski** [artsy/metaphysics#101]
cc @cavvia

**Comment by dzucconi** [comment]
Which are these?

You can currently get trending artists off a gene: https://github.com/artsy/metaphysics/blob/536b14939166ffbc027ffe5b18514bbb5fc72c91/schema/gene.js#L37-L52

**Comment by broskoski** [comment]
for instance: 
http://delta.artsy.net/?method=fetch&name=artist_follow_2t&n=40
http://delta.artsy.net/?method=fetch&name=artist_save_2t&n=40
http://delta.artsy.net/?method=fetch&name=artist_search_2t&n=40

**Comment by alloy** [comment]
It’s a doner
