### ISSUE TITLE
Preparations for use in Relay

### ISSUE THREAD

**Issue by broskoski** [artsy/metaphysics#134]
I haven't researched at all what is needed here, but whatever work is needed to make metaphysics work nicely with Relay will be needed for both web and mobile.

----

[Updated by @alloy]

- [x] Add [Global Object Identification](https://facebook.github.io/relay/graphql/objectidentification.htm).
  - [x] Need to change the `id` fields to be a composite key, so that the type and specific instance can be inflected from it. E.g. `Artist#banksy`. The common implementation deployed in the GraphQL community also Base64 encodes that key.
  - [x] Ensure existing clients use the appropriate ID field. Which, for those not using Relay atm, means they probably need to use `_id`, which maps to the Gravity ID. However from short discussion with @joeyAghion, it seems like searching by `_id` could be a problem, because only _some_ models would support searching by slug on that field. Alternatively we’ll have to add e.g. `gravityID`, which would be the equivalent of `id` right now.

- [ ] Expose associations as [connections](https://facebook.github.io/relay/graphql/connections.htm), which allow for slicing and paginating.

- [ ] See if we need to do anything else to support [deferring query fragments](https://github.com/facebook/relay/issues/288).

**Comment by dzucconi** [comment]
https://github.com/graphql/graphql-relay-js

**Comment by alloy** [comment]
Aye aye. So basically, since our current sprint where the new artist view is scheduled is slated for 21st of March, this means I’d need to be able to use Relay with metaphysics before then, e.g. 16th.

**Comment by orta** [comment]
@alloy where did this end up ( I know we use relay in Eigen now )

**Comment by alloy** [comment]
We do use Relay, but there are certain features we can’t use yet. I will update the original comment with a TODO list.

**Comment by alloy** [comment]
@mzikherman Can you shed some light on that issue with `_id` on Gravity supporting search by slug, but only on some models?

**Comment by alloy** [comment]
Moved connections part to a new ticket https://github.com/artsy/metaphysics/issues/367
