### ISSUE TITLE
Tune memory usage

### ISSUE THREAD

**Issue by dzucconi** [artsy/metaphysics#141]
![](http://static.damonzucconi.com/_capture/cP6FPVbTu2.png)

![](http://static.damonzucconi.com/_capture/JABwHSe5kK.png)

Memory usage generally tends to stay within the bounds of Heroku's Standard-1X dyno limits but occasionally there is some kind of runaway spike. This doesn't appear to correlate at all with throughput/reqs which were flat during that last spike

**Comment by craigspaeth** [comment]
(╥﹏╥) lmk if you want help with this. I saw another good article about debugging memory in Node recently.

**Comment by dzucconi** [comment]
Weird spike of throughput, then all of a sudden, swapping

![](http://static.damonzucconi.com/_capture/AbaWkNxhOq.png)

**Comment by craigspaeth** [comment]
Also just a thought.. `global.Promise = require('bluebird')` :stuck_out_tongue_winking_eye:

**Comment by dzucconi** [comment]
gooooood suggestion

**Comment by dzucconi** [comment]
I think we just needed a bit more headroom. I switched from 2x512mb dynos to 1x1gb dyno 2 days ago and it looks pretty good. I'm sure switching to bluebird didn't hurt either.
