### ISSUE TITLE
OSS?

### ISSUE THREAD

**Issue by orta** [artsy/metaphysics#2]

**Comment by ashfurrow** [comment]
Looks like this is good to close :tada:

**Comment by dzucconi** [comment]
:cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool:
:cool::cookie::cookie::cookie::cookie::cookie::cool::cookie::cool::cool::cool::cool::cookie::cool::cookie::cool::cool::cool::cool::cookie::cool:
:cool::cool::cool::cookie::cool::cool::cool::cookie::cool::cool::cool::cool::cookie::cool::cool::cookie::cool::cool::cookie::cool::cool:
:cool::cool::cool::cookie::cool::cool::cool::cookie::cookie::cookie::cookie::cookie::cookie::cool::cool::cool::cookie::cookie::cool::cool::cool:
:cool::cool::cool::cookie::cool::cool::cool::cookie::cool::cool::cool::cool::cookie::cool::cool::cool::cookie::cookie::cool::cool::cool:
:cool::cool::cool::cookie::cool::cool::cool::cookie::cool::cool::cool::cool::cookie::cool::cool::cookie::cool::cool::cookie::cool::cool:
:cool::cool::cool::cookie::cool::cool::cool::cookie::cool::cool::cool::cool::cookie::cool::cookie::cool::cool::cool::cool::cookie::cool:
:cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool::cool:

**Comment by ashfurrow** [comment]
![](http://media1.giphy.com/media/vtVpHbnPi9TLa/giphy.gif)
