### ISSUE TITLE
Specify time zone defaults.

### ISSUE THREAD

**Issue by alloy** [artsy/metaphysics#227]
Regarding the `exhibition_period` field added in #226, and dates in general, we should make it possible to return these taking the user’s time zone into account. My thoughts are:

- [x] Make date formatting fields take an optional zone. https://github.com/artsy/metaphysics/blob/c70b0f8c0afc8ab739883973392fe38294ccde6d/schema/fields/date.js
- [x] Set a default zone for the duration of the request through a [TIMEZONE HTTP header](https://tools.ietf.org/html/draft-sharhalakis-httptz-05). This would be particularly helpful with Relay clients, as it means we can specify the header that the network layer should use in a single configuration place.
- ~Fallback to a default that makes sense for our data. Gravity’s default is `America/New_York`.~

**Comment by dzucconi** [comment]
Re: `exhibition_period`: it wouldn't make a ton of sense to say an opening is at 8pm your time EST when the gallery is in Tokyo—which is why I thought we just use UTC across the board?

**Comment by alloy** [comment]
I'm mainly thinking about the zones where a date might not be the same as the UTC one.

This is more important for another thing I'll be adding tomorrow, which is a status message like 'Opening Today', which is kinda lame when a show is not actually closing 'today' in that user's zone.

**Comment by dzucconi** [comment]
I think what we do though is use UTC, then ignore time zones altogether, just treat it as a raw date.

Though I see the point about the today/tomorrow kind of confusion.

**Comment by alloy** [comment]
For Emission it definitely makes sense to set a default through a header.

**Comment by 1aurabrown** [comment]
I don't totally understand how this would be different from what we already do on the client with, for example, auctions. I'm happy to pick this up though! Just want to 'get it'.

**Comment by alloy** [comment]
Instead of specifying the client's TZ in [each field that returns a date](https://github.com/artsy/metaphysics/blob/0a5e5ea1aee078a6c7dd627420e8c4c611abb326/schema/fields/date.js#L11:L13), the client should be able to specify a HTTP header with its TZ and then MP should use that as the default for all such date fields

**Comment by 1aurabrown** [comment]
got it!

**Comment by 1aurabrown** [comment]
Just wanted to clarify some stuff about the formatting of dates which might determine implementation. Do we want to use words like 'Yesterday' and 'Today' and 'Tomorrow' when applicable? moment.js has two different functions, one which accepts a format, and applies it to the date, and once which can be customized with several formats, depending on if the moment is long in the past, within the past week, yesterday, today, tomorrow, within the coming week, or farther in the future. I'm sure we'd often want to use the former, which is how our current implementation works, but if we want to sometimes say words like 'Yesterday/Tomorrow' and sometimes say things like 'Friday June 8, 2017', we would want to use the latter, it seems. This means maybe two types of date fields with different parameters and resolve methods, or one field with some way of switching between these two modes based on parameters.

Second, our existing date field has an optional `timezone` parameter, which we'd be replacing with the timezone from the header, obviously. If `timezone` is not supplied we just format the date from gravity without offsetting for time zone. Should we preserve the way this is optional or always apply timezone info from the header to any date field?

**Comment by 1aurabrown** [comment]
Also assuming we want a version of this for date ranges, which can also accept a format?
