### ISSUE TITLE
IMPULSE_APPLICATION_ID

### ISSUE THREAD

**Issue by idkjs** [artsy/metaphysics#2704]
Where can I get and `IMPULSE_APPLICATION_ID` to get this program to run? Currently getting the followin error after installing and running.

Thank you.
```sh
7:11:56 PM web.1       |      throw new Error(`You need to have the ENV var ${key} set up - check out ${file}.`);
7:11:56 PM web.1       |      ^
7:11:56 PM web.1       |  Error: You need to have the ENV var IMPULSE_APPLICATION_ID set up - check out .env.example.
```

**Comment by damassi** [comment]
Hi @idkjs - if you rename `.env.oss` to `.env` things _should_ work: https://github.com/artsy/metaphysics/blob/master/.env.oss

**Comment by idkjs** [comment]
ok. Will try and report back. Thank you.
