### ISSUE TITLE
We should paginate bidders in causality JWT

### ISSUE THREAD

**Issue by devangt** [artsy/metaphysics#312]
The key here was that if there are more than 10 auctions a user is registered for than we didn't get the correct registration status putting the user in a pending state of registration

**Comment by acjay** [comment]
For this, we shouldn't be iterating through the list of all Bidders for the User -- we should instead check whether a Bidder exists for the given Sale. If using `co` (which helps make the dependent fetch a little nicer), we could rewrite https://github.com/artsy/metaphysicshttps://github.com/artsy/metaphysics/blob/master/schema/causality_jwt.js#L47-L71 as:

```
return co(function* () { 
  const [sale, me] = yield Promise.all([
    gravity(`sale/${options.sale_id}`)
    gravity.with(accessToken)('me')
  ]);
  const bidder = gravity.with(accessToken)(`me/bidders?sale_id=${sale._id}`);

  if (bidder) {
    return jwt.encode({
      aud: 'auctions',
      role: 'bidder',
      userId: me._id,
      saleId: sale._id,
      bidderId: bidder.id,
      iat: new Date().getTime(),
    }, HMAC_SECRET);
  } else {
    return jwt.encode({
      aud: 'auctions',
      role: 'observer',
      userId: me._id,
      saleId: sale._id,
      bidderId: null,
      iat: new Date().getTime(),
    }, HMAC_SECRET);
  }
});
```

I don't have Metaphysics all set up on my machine to try this out.

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
