### ISSUE TITLE
Add an Artsy user authentication page before GraphiQL

### ISSUE THREAD

**Issue by orta** [artsy/metaphysics#333]
This should fix the problem related to https://github.com/artsy/metaphysics/issues/279 /cc @craigspaeth

**Comment by alloy** [comment]
@orta Do it!

**Comment by mzikherman** [comment]
sorry @orta @l2succes is taking this!

**Comment by 1aurabrown** [comment]
I'm taking this since it's been sitting here, someone tell me if they have any objections.

**Comment by mzikherman** [comment]
@l2succes I think you mentioned you had this in-progress on a branch, but was blocked b/c of the redirect issue?

I just enabled redirects for this client app (taking credentials from Heroku) to `localhost:5001` (note 5001 port). Once we have that working on your branch we can PR it, and include a migration in the PR to enable redirects to `metaphysics-production.artsy.net` and `metaphysics-staging.artsy.net`.

@l2succes do you want to finish this up? Alternatively, feel free to push what you have in a branch and me or @1aurabrown can carry it across the finish line! ✊

**Comment by l2succes** [comment]
@mzikherman Perfect, I'll go ahead give try it a shot with `localhost:5001`.  I'll let you know if anything comes up but should be able to finish it up in the next day. I'm also working on some stuff on emission so if it takes too long I'm happy to pass it to you @1aurabrown.

**Comment by joeyAghion** [comment]
I'm concerned about sending the public to our staging environment. We discussed this in a few separate channels, but I'll try to summarize:
* I'm _especially_ concerned about offering a UI for easily querying our staging API. We track API clients for tracking and potential rate-limiting purposes, but all of these requests appear as coming from Metaphysics.
* Even setting that aside, the staging environment gets a periodic copy of production data, and is used for testing, staging infrastructure changes, etc. I.e., it's frequently broken and I wouldn't want to have to support a whole new population of users.
* It's not scaled for public usage.
* This adds to the many varied uses of the staging environment. It already serves as a sandbox for slightly stale data-scripting, supports nightly automated smoke-testing, hosts frequent mock-auctions, and [finally] stages feature work that's pending deploy.

**Comment by alloy** [comment]
I would be very surprised if more than the occasional person that’s trying to learn GraphQL would use this, other than maybe a small uptick of the 50 or so people that will fave one of the tweets (it’s more likely that more people will fave/retweet than actually use the UI).

I hear you on not being able to track that well, though, as it’s all just requests from MP. For now, can we just keep an eye on requests coming from MP not exploding?
