### ISSUE TITLE
[deploy] Send notifications to Slack

### ISSUE THREAD

**Issue by alloy** [artsy/metaphysics#340]
We need Semaphore to send deploy notifications to ~~#platform-alerts~~ #platform-machines (and possibly #web, #gmv-ios-dev) so that:
- others _can_ always know that a deploy occurred
- people looking at #platform-alerts can correlate deploys to :fire:

**Comment by joeyAghion** [comment]
I'd actually send these to #platform-machines or an analogous channel monitored by the Web practice. We try to keep #platform-alerts limited to attention-demanding notifications, since -machines can get noisy.

**Comment by mzikherman** [comment]
Deploy notifications _were_ being sent to #web, but were disabled yesterday morning (not sure why).

I like them in #web, that channel is overall not too chatty so it wasn't getting lost OR interfering w/ noise.

**Comment by alloy** [comment]
> I like them in #web, that channel is overall not too chatty so it wasn't getting lost OR interfering w/ noise.

I guess there’s value in adding them to both locations? If that’s possible at all.

**Comment by alloy** [comment]
It’s a doner
