### ISSUE TITLE
Adopt inclusive language

### ISSUE THREAD

**Issue by kathytafel** [artsy/metaphysics#3584]
in 

- [x] src/schema/v1/home/fetch.ts
- [x] src/schema/v2/home/fetch.ts
- [x] /index.js
- [x] src/config.ts
- [x] src/lib/graphqlErrorHandler.ts
- [x] src/schema/v2/fair.ts
- [x] src/schema/v2/show.ts

per https://github.com/artsy/README/issues/427

**Comment by dblandin** [comment]
Both PRs are merged! Going to go ahead and close this ticket.
