### ISSUE TITLE
[Home] Artist rail data missing

### ISSUE THREAD

**Issue by mennenia** [artsy/metaphysics#360]
When querying for the homepage modules, currently there are no artists based modules in the results, just artworks. 

E.g.: there are results like "Works by Iconic Artists" containing artworks, yet no modules like "Recommended Artists to Follow" that would contain a list of artists.

**Comment by broskoski** [comment]
Yeah we haven't gotten here yet but we were planning on tackling this outside of the HomePageModule schema. The form factor (in our mockups there are three different "tabs") and  the data coming back is going to be a bit different. Also, the rail is always going to be present no matter what. Definitely open to other suggestions but this rail feels different enough that it should be handled elsewhere.

**Comment by alloy** [comment]
I see, so on web you will have 1 rail with three tabs, whereas on mobile we will have 3 rails and no tabs. And you’re right, they will always be at the same locations, so we could just insert those ourselves.

Having said that, I would prefer that we nest it under the `home_page` field, as it _is_ still a home page specific thing. I realise that you might not be using that field yet, but maybe that can be changed and we can get rid of the `home_page_module` and `home_page_modules` root fields?

**Comment by alloy** [comment]
I do feel like the existing `HomePageModule` type and `home_page.module` field (plus the plural ones) should probably be renamed to reflect that they’re about artworks as well then. What are your thoughts?

If needed we can temporarily duplicate the existing code and use new naming under the `home_page` root field and you can shift over at your own leisure?

**Comment by broskoski** [comment]
I'm flexible. This schema is already pretty weird, using a `GraphQLUnionType` to switch on the results (whether artwork or artists) is just a drop in the bucket IMO.

The difference between 3 rails vs 1 tabbed rail is a bit too weird though, I wish this could be something like a separate schema of its own that could be optionally included in the homepage rails.

**Comment by mennenia** [comment]
If you were to fetch someone's home feed data to display you'd almost expect in the case of web there to be a dictionary of the three artist rails, whereas for mobile it to be in the list of modules. So it's up to the client to request the content they need and display it where appropriate (e.g. in tabs, or various rails)

In which case I was thinking of one of the following two options:

- `home_page`
	- `works_modules`
	- `artist_modules`
	- any other potential content modules (e.g. galleries?)

OR

we take out `HomePageModules` and for something like:
- `ArtworkModules` / `InitialArtworkModules` / `FeaturedArtworkModules` / `RecommendedArtworkModules`
- `ArtistModules`, and the other possible variations

I actually quite like having a home root and then various content inside of it (approach 1), because I worry that the second way could get confused with other content, and the goal _is_ for it to live on the home page after all.

**Comment by alloy** [comment]
> - `home_page`
>	- `works_modules`
>	- `artist_modules`
>	- any other potential content modules (e.g. galleries?)

This is my suggestion as well and what I’m building at the moment.

**Comment by alloy** [comment]
Such a doner
