### ISSUE TITLE
Add more nuance to modules API for number and type of rails

### ISSUE THREAD

**Issue by sarahscott** [artsy/metaphysics#410]
Currently, we can use the [max_rails](https://github.com/artsy/metaphysics/blob/master/schema/home/home_page_artwork_modules.js#L31) arg to specify how many rails we want, but we have no control over what the extra rails are. The mobile home spec calls for unlimited generic gene rails, for example, but not necessarily unlimited rails of any type. We've solved this temporarily by setting `max_rails` to 999 (yolo) but it'd be nice to specify exactly what we need.

**Comment by alloy** [comment]
This got done in https://github.com/artsy/metaphysics/commit/84e0a592fe2f303372c5fbb79434c3ce48032cfe
