### ISSUE TITLE
Proposition: create static API reference 

### ISSUE THREAD

**Issue by pelletier197** [artsy/metaphysics#4250]
Hello! I am the maintainer of a documentation tool called [Magidoc](https://github.com/magidoc-org/magidoc), an open source software that auto-generates static GraphQL API documentation references. 

I would like to propose to integrate Magidoc into this project. This would allow users of the API to easily get an overview of everything they can do, but it can also contain other documentation that may be useful to use your API, authentication, URLs, etc. You can write custom content and put anything you want, and let the rest of the documentation be auto-generated.

If you want to see an example, here is a link to a [demo website](https://magidoc-carbon-multi-page.netlify.app/welcome).

I am also willing to help you integrate it if you want, and this can be deployed on any static content delivery like GitHub pages, Netlify, Vercel, s3, etc.

Let me know what you think about the idea and feel free to close the issue if you're not interested. Thank you!

**Comment by damassi** [comment]
Thanks for the heads up! When we need docs we will consider this.

**Comment by pelletier197** [comment]
Great, let me know then if you need help. Thank you!
