### ISSUE TITLE
Remove Warning about Typescript Version

### ISSUE THREAD

**Issue by kajatiger** [artsy/metaphysics#4808]
Let's remove this warning:
```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.2.0

YOUR TYPESCRIPT VERSION: 4.6.4

Please only submit bug reports when using the officially supported version.
```

**Comment by damassi** [comment]
@kajatiger - I worry that this issue will get lost here. Can you file in the [Web Practice JIRA board](https://artsyproduct.atlassian.net/jira/software/projects/WP/boards/97)? 

Otherwise, if you feel like fixing, upgrading `@typescript-eslint` to the latest should do it.

**Comment by kajatiger** [comment]
@damassi is the web practice board actively used?

**Comment by kajatiger** [comment]
Created issue on Jira

**Comment by damassi** [comment]
🙏
