### ISSUE TITLE
[Homepage] Add missing artworks rail for artist on which basis other artist is suggested

### ISSUE THREAD

**Issue by alloy** [artsy/metaphysics#490]
As noted by @briansw [here](https://github.com/artsy/force/issues/79#issuecomment-265288454), we currently only show the rail with artworks for the suggested artist, but are omitting the artwork rail for the artist that the suggestion is based on.

**Comment by broskoski** [comment]
@briansw is this rail supposed to use the artist the `relatedArtists` rail is based on? Or should it use a completely different followed artist altogether?

**Comment by briansw** [comment]
i think we're capping the success of it a little if we always keep them in sync. ie, we display a weak follow for the user and now the suggestion is also based on the weak follow. if it’s a lot of work to make an extra request just do it that way for now though.

**Comment by alloy** [comment]
@briansw I’m slightly surprised by that, in the sense that I can totally imagine the case where I have no recollection that I follow the artist that the rail is based on. I do get your argument regarding possibly surfacing a weak suggestion, but in that case I wonder if the “based on X” copy is helpful/good enough.

**Comment by alloy** [comment]
@briansw bump

**Comment by briansw** [comment]
Let's keep the copy "Based on X" even though the previous rail won't be directly related, I think it still helps to contextualize why we're suggesting the artist.
