### ISSUE TITLE
[Optimize] See if the Apollo Optics data gives us good insights.

### ISSUE THREAD

**Issue by alloy** [artsy/metaphysics#515]
https://optics.apollodata.com/service/metaphysics

@mzikherman @xtina-starr Can you take a stab today at pairing up and see if you can use the Apollo Optics data to actually improve the performance of one of the more costly resolvers/fields?

**Comment by alloy** [comment]
@mzikherman and @xtina-starr were able to do some small optimizations, so we decided to give it a longer try, if the price is right.

@xtina-starr can you send out that email today?

**Comment by xtina-starr** [comment]
@alloy sure thing, that's on my to do list.

**Comment by xtina-starr** [comment]
Just finished a call with the folks at Optics. This tool seems to be pretty early in the development process and doesn't quite meet the needs of our particular use case. We were looking for something that could provide daily monitoring (offering an alert component and an efficient way to determine performance spikes). We also felt this tool would be more helpful if it included the ability to add annotation and could sort by throughput. The price we'd fall into ($599/month) was a bit high for the offering so it makes sense to pass for now. However, they were pretty open and receptive to our feedback so perhaps this is something we can revisit at a later date once it's more built out.
