### ISSUE TITLE
Log/surface errors

### ISSUE THREAD

**Issue by mzikherman** [artsy/metaphysics#54]
This thread: https://github.com/artsy/force-private/pull/3774#discussion_r44986905

Basically, I think we should be logging whenever leafs are erroring (for a particular query). That way, instead of waiting to notice that something is broken or missing somewhere down the line, we can stay more on top of inconsistencies in our data or API responses, etc.

Maybe those queries should actually return non-successful status codes and it can be logged in NewRelic? If we want them to still be successful in prod, maybe we can have some middleware that sends any errors and the related queries to NewRelic or wherever.

**Comment by alloy** [comment]
Yes, I agree we need to do this. Right now there are errors being served to Eigen that will silently break views, we should now of these data issues asap.

I don’t think we should return non-successful status codes, but it should be possible to just log errors with NewRelic [through their API](https://github.com/CocoaPods/trunk.cocoapods.org/blob/770269223fee22fb744477ffe3194bb4776c910c/app/controllers/api_controller.rb#L52-L54) directly.

**Comment by alloy** [comment]
Seems like we should be using [this API](https://github.com/artsy/artsy-newrelic/blob/e516296fde0f1edf2f41286eadf0267dde850f7a/index.js#L22).
