### ISSUE TITLE
Retrieve confirmed purchases.

### ISSUE THREAD

**Issue by alloy** [artsy/metaphysics#552]
In addition to https://github.com/artsy/metaphysics/issues/549, we also want to be able to include whether or not the collector bought the work.

We’re not entirely sure where this data lives and if there’s already an API from where to fetch this. Is it Impulse? @ashkan18 do you know?

**Comment by alloy** [comment]
Still needs estimation.

**Comment by ashkan18** [comment]
Currently this data is [a status](https://github.com/artsy/gravity/blob/master/app/models/domain/inquiry_request.rb#L18) on `InquiryRequest` model, we are thinking of moving that out of Gravity and move it to Impulse but thats not happening yet.

This status is currently set manually by Stas's team in Torque.

**Comment by alloy** [comment]
Thanks, @ashkan18 👍

**Comment by ashkan18** [comment]
Not sure if it makes it easier in this case, but what also worth mentioning is, updating an inquiry request to that status will [create](https://github.com/artsy/gravity/blob/master/app/models/domain/artwork_inquiry_request.rb#L27-L31) a new [`Purchase`](https://github.com/artsy/gravity/blob/master/app/models/domain/purchase.rb). If we are trying to show if a purchase has happened by this collector on specific artwork, searching `Purchase` model might be faster.

**Comment by alloy** [comment]
We’re fetching all of the inquiries and want to additionally know their statuses, so this status field seems perfect.

**Comment by 1aurabrown** [comment]
i think we determined that this issue is redundant or obsolete given that we will be launching the collector loyalty email only to a subset of users who don't have inquiries that are not confirmed purchases. i'm going to close.
