### ISSUE TITLE
Fix notifications without artworks

### ISSUE THREAD

**Issue by sarahscott** [artsy/metaphysics#600]
They shouldn't be sent to clients and maybe indicate an underlying issue?

![screen shot 2017-04-07 at 12 13 43 pm](https://cloud.githubusercontent.com/assets/2712962/24796059/c8d8d184-1b8b-11e7-9fa4-6869f573844d.png)

![simulator screen shot apr 7 2017 12 12 17 pm](https://cloud.githubusercontent.com/assets/2712962/24795953/7a15340c-1b8b-11e7-80ef-694424fb670a.png)

**Comment by mzikherman** [comment]
Unfortunately we don't ever 'recall' notifications. So if a notification was generated for you, but the artwork was later unpublished, you might see behavior like this.

**Comment by sarahscott** [comment]
Ah ok. So for now maybe we just check in the client for empty `artworks` arrays?

**Comment by mzikherman** [comment]
Yea, I probably should have mentioned that earlier, but b/c of the big perf impact to try to 'undo' notifications (based on artworks being unpublished/deleted), we never did that.

So yea, I think we need to be defensive about that on the client (not rendering the feed item if there are no artworks). Is that ok to do in RN or does it not play nicely?

**Comment by sarahscott** [comment]
[Easy-peasy](https://github.com/artsy/emission/pull/477/files#diff-10b56765fff6f55979a359a03190f0a2R24)
