### ISSUE TITLE
[MSG] Add hasActiveBids and hasConversations flags

### ISSUE THREAD

**Issue by alloy** [artsy/metaphysics#687]
The Inbox container component should be able to check if the user has active bids or conversations. This should be implemented in such a way that during the resolve request the DataLoader instance that fetches the actual bid and conversation details is re-used to provide these booleans (i.e. don’t make multiple backend requests to determine the booleans and fulfill the detail requests).

See https://github.com/artsy/emission/pull/664/files#r126397449

**Comment by alloy** [comment]
To be clear, this involves reworking the current [conversations](https://github.com/artsy/metaphysics/blob/99ce253ddad4b556264987c1015f4b383772c7b0/schema/me/conversations.js#L24-L29) and [auctions lot standings](https://github.com/artsy/metaphysics/blob/99ce253ddad4b556264987c1015f4b383772c7b0/schema/me/lot_standings.js#L27-L36) data loading to use separate DataLoader instances, which they don’t do at atm.

**Comment by jonallured** [comment]
@alloy in light of #717, I'm not 100% sure where this stands. I think what's left to resolve is how Impulse can tell us total counts, is that right? The work to get the loaders reorganized is complete, correct?

I had some work on this one locally, so I might push it up to see if there's anything worthwhile there.

**Comment by alloy** [comment]
@jonallured Possibly the largest work item is to make Impulse return counts. The work done in #717 should definitely make it somewhat simpler to do the MP side of things.

> I had some work on this one locally, so I might push it up to see if there's anything worthwhile there.

Sounds good 👍

**Comment by jonallured** [comment]
Ok, after rebasing and realizing how simple this might actually be, I pushed up a red commit here:

https://github.com/jonallured/metaphysics/commit/2dcce5a52accde9616434e48c18aa52dbf66c06a

I'm getting `null` back instead of false/true, so I'm doing something wrong, but I'm wondering if Impulse returning counts really matters? If you have no conversations, then the count doesn't matter and if you do, then we just care that its more than zero, no?

**Comment by alloy** [comment]
If there are no counts then it doesn’t matter indeed, but if there are conversations then we are sending a bunch of data over the wire that doesn’t end up being used. Maybe that’s ok for now, but I’ll defer to @ashkan18 for that decision.

**Comment by jonallured** [comment]
Cool, I'll defer to him, but I mentioned this to him last week and he pointed me towards the `PaginatedPresenter`:

https://github.com/artsy/impulse/blob/fcb2353b1a8261d2811f83f170135f90991e8906/app/api/v1/presenters/paginated_presenter.rb

Which gets included here:

https://github.com/artsy/impulse/blob/fcb2353b1a8261d2811f83f170135f90991e8906/app/api/v1/presenters/conversations_presenter.rb

So, if I'm reading this right, I think there's a property in that JSON object called `total_count` that we could be using, but there's not a way to suppress the rest of the data being sent.

**Comment by mzikherman** [comment]
In that case, I would make the request with `page=1&size=0` params to ensure nothing is loaded or sent over the wire (+ hopefully the `total_count` is still accurate).

That's a pattern we've used before when wanting to make a call _just_ for counts.

**Comment by jonallured** [comment]
So would that be something like this:

```js
    has_conversations: {
      type: GraphQLBoolean,
      resolve: (root, options, request, { rootValue: { conversationsLoader } }) => {
        return conversationsLoader({ page: 1, size: 0 }).then(({ total_count }) => {
          return total_count > 0
        })
      },
    },
```

Can I pass request options like that? Or do I now need to update the `conversationsLoader` to use them?

**Comment by alloy** [comment]
That should work 👍

**Comment by alloy** [comment]
So the count gets added to the main response rather than a response header (like gravity does) ?

**Comment by ashkan18** [comment]
Sorry for being late on this, somehow missed github notification when i was mentioned here. Yes, Impulse adds `total_count` as part of the response, kind of follows Hypermedia schema, we could also have something in the header if that makes the job easier on this side.

**Comment by alloy** [comment]
Does it _always_ include that field or do we still need to request it?

**Comment by tayapage6** [comment]
@alloy was this for team swap experience only or do we actually need to do this as a showstopper?

**Comment by alloy** [comment]
@tayapage6 It’s not a showstopper at all, it’s mainly tech debt / maintenance work.

**Comment by jonallured** [comment]
Heyo! I'm going to close this for now. It's old and maybe not worth pursuing anymore? If someone disagrees, feel free to reopen!! ❤️
