### ISSUE TITLE
[Stitching] Metaphysics should remain resilient (w/ respect to introspection and start up)

### ISSUE THREAD

**Issue by mzikherman** [artsy/metaphysics#816]
This is in the context of schema stitching.

We should keep in mind that Metaphysics should be able to startup, at the very least, no matter the state of the underlying services, even if they are down and not able to respond to an introspection query.

If we query underlying services upon Metaphysics boot- this might require some finagling. Also, it would then require restarting Metaphysics (to get the correct schema), when the other service has been fixed and is back up.

This might be a pro for using a regularly synced/dumped file (or multiple files for different privileged schemas), to make the link between Metaphysics and other services less brittle.

**Comment by orta** [comment]
We opted for dumped SDL files
