### ISSUE TITLE
enums should be caps

### ISSUE THREAD

**Issue by 1aurabrown** [artsy/metaphysics#83]
https://facebook.github.io/graphql/#sec-Enum-Value

**Comment by alloy** [comment]
E.g. https://github.com/artsy/metaphysics/blob/0d7c2cb996c707071103a9ea0d36aa5327aaf5c8/schema/input_fields/event_status.js
https://github.com/artsy/metaphysics/blob/0d7c2cb996c707071103a9ea0d36aa5327aaf5c8/schema/sorts/artist_sorts.js

And then this should probably be a Danger rule. /cc cough @orta cough
