### ISSUE TITLE
[stitching] Dealing with type name ambiguity/conflicts

### ISSUE THREAD

**Issue by alloy** [artsy/metaphysics#833]
Please see https://github.com/apollographql/graphql-tools/issues/495#issuecomment-346607677

We [shortly discussed](https://artsy.slack.com/archives/C1HH3KNJG/p1510857274000641) this previously. We should continue that discussion to determine what would be good enough for us.

cc @orta @joeyAghion

**Comment by orta** [comment]
#1028 has some examples of this with consignments

**Comment by orta** [comment]
Yeah, I'm closing now there's an implementation of how to do this, and a general discussion in the guides - https://github.com/artsy/guides/blob/master/guides/GraphQL-Schema-Design.md
