### ISSUE TITLE
Tracking of upstream urls breaks partners loader

### ISSUE THREAD

**Issue by anandaroop** [artsy/metaphysics#839]
Re:
- artsy/collector-experience/issues/730
- artsy/collector-experience/issues/731
- [Slack report #1](https://artsy.slack.com/archives/C02CAB1KW/p1511783060000157)
- [Slack report #2](https://artsy.slack.com/files/U030DN7J1/F87HTSQLF/screen_shot_2017-11-28_at_15.46.13.png)

www.artsy.net/galleries shows a location-based carousel ("Featured Galleries near _&lt;your current location&gt;_") which is currently including invalid results:

- partners without published profiles (thus missing cover images)
- partners not near the requested location

![invalid](https://user-images.githubusercontent.com/140521/33350771-9e039de4-d46e-11e7-8fba-f350a3fa3dea.png)

That rail is backed by [this metaphysics query in Force](https://github.com/artsy/force/blob/master/desktop/apps/galleries_institutions/queries/location_carousel_query.coffee), which you can view the results of in [this Graphiql query](https://metaphysics-production.artsy.net/?operationName=location&query=query%20location(%24near%3A%20String%2C%20%24type%3A%20%5BPartnerClassification%5D)%20%7B%0A%20%20primary%3A%20partners(eligible_for_listing%3A%20true%2C%20eligible_for_primary_bucket%3A%20true%2C%20sort%3A%20RANDOM_SCORE_DESC%2C%20default_profile_public%3A%20true%2C%20near%3A%20%24near%2C%20type%3A%20%24type)%20%7B%0A%20%20%20%20...partner%0A%20%20%7D%0A%20%20secondary%3A%20partners(eligible_for_listing%3A%20true%2C%20eligible_for_secondary_bucket%3A%20true%2C%20sort%3A%20RANDOM_SCORE_DESC%2C%20default_profile_public%3A%20true%2C%20near%3A%20%24near%2C%20type%3A%20%24type)%20%7B%0A%20%20%20%20...partner%0A%20%20%7D%0A%7D%0A%0Afragment%20partner%20on%20Partner%20%7B%0A%20%20id%0A%20%20name%0A%20%20initials%0A%20%20locations(size%3A%2015)%20%7B%0A%20%20%20%20city%0A%20%20%7D%0A%20%20profile%20%7B%0A%20%20%20%20id%0A%20%20%20%20href%0A%20%20%20%20image%20%7B%0A%20%20%20%20%20%20cropped(width%3A%20400%2C%20height%3A%20266%2C%20version%3A%20%5B%22wide%22%2C%20%22large%22%2C%20%22featured%22%2C%20%22larger%22%5D)%20%7B%0A%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&variables=%7B%0A%20%20%22near%22%3A%2240.7127837%2C-74.0059413%22%2C%0A%20%20%22type%22%3A%5B%22GALLERY%22%5D%0A%7D
):

Note the missing cities and empty profiles:

![bad](https://user-images.githubusercontent.com/140521/33350991-ab228106-d46f-11e7-9aae-cff4959713a7.png)

Using `git bisect` I isolated the problem to https://github.com/artsy/metaphysics/commit/10e060aa95a9d05b9d237bb230c848ecc00da02b.

Something in that commit has mangled the upstream Gravity request url, which in Papertrail shows up as this:

![partners](https://user-images.githubusercontent.com/140521/33351285-f87d7310-d470-11e7-9241-a9b59af24ffb.png)

I am able to "fix" the problem by undoing this one change in that commit…

<img width="1145" alt="undo" src="https://user-images.githubusercontent.com/140521/33351308-26542d7e-d471-11e7-926f-96fce40b3a68.png">

… but I am not at all sure that is a legit change.

Happy to pair, though I will be out tomorrow (Wed) 😕 

cc: @orta @yuki24

**Comment by mzikherman** [comment]
It's an incorrect use of that loader, its serializing the string `partners`.

It should just be `partnersLoader(options)`, and not `partnersLoader("partners", options)`. That should fix it.

**Comment by joeyAghion** [comment]
Great find!

**Comment by mzikherman** [comment]
Yea, excellent sleuthing work, as usual.

Looks like https://staging.artsy.net/galleries is fixed!

<img width="783" alt="screen shot 2017-11-28 at 5 49 46 pm" src="https://user-images.githubusercontent.com/1457859/33353299-2509fffc-d47b-11e7-9449-45af7115388d.png">

**Comment by anandaroop** [comment]
Omg, thanks for the quick fix @mzikherman ! 

Just confirmed that it's fixed on https://staging.artsy.net/galleries 🎉

**Comment by starsirius** [comment]
Nice! Thanks for quick fix, @anandaroop and @mzikherman! 🎉

**Comment by yuki24** [comment]
Thanks for taking care of this! @anandaroop @mzikherman
