### ISSUE TITLE
Support different caching needs

### ISSUE THREAD

**Issue by joeyAghion** [artsy/metaphysics#852]
The current unauthenticated+caching data-loader may be fast for clients, but doesn't help backing systems at all because it immediately attempts to refresh the cache on each request. In many cases this is much more aggressive than necessary. An example:

The new artist highlights component depends on several API requests to fill out its data. This data (auction record, gallery representation, and presence in institutional collections) changes very slowly--on the order of _years_--and will be rendered with every load of an artwork page. It doesn't make sense to make 3 additional API requests for every artwork page; instead we could allow the data to be, say, up to 24 hours stale.

It would be great if the data-loaders (or a new one) optionally let callers specify the cache expiration.

**Comment by alloy** [comment]
Yup, sounds way overdue. It should be fairly straightforward to add an optional expiration value per key [here](https://github.com/artsy/metaphysics/blob/b4f1f06cbe5b68aeb8206ea9a9698ded2de0bad6/lib/cache.js#L46) and allow the data loaders to define specific cache expiration per endpoint.

**Comment by joeyAghion** [comment]
Hmm... per endpoint? That might be a problem, because we wouldn't want the staleness to apply (in the example's case) to _all_ requests that retrieve artists, partner-artists, or auction results. We _would_ want the `highlights` schema's results (or the requests originating there) to be allowed to be stale though.

You see what I mean? The caching I had in mind would need to be applied closer to the resolvers.

**Comment by alloy** [comment]
Oh that’s fine too, users of the data loaders could also pass in a custom expiration that would override any other defaults. That’s the `pathAPIOptions` [here](https://github.com/artsy/metaphysics/blob/b4f1f06cbe5b68aeb8206ea9a9698ded2de0bad6/lib/loaders/api/loader_without_authentication_factory.js#L32).
