### ISSUE TITLE
Per request caching option

### ISSUE THREAD

**Issue by dzucconi** [artsy/metaphysics#9]
Would want to be able to do something like:

```
{ artwork(id: "robert-longo-untitled-pl-8-from-men-in-the-cities-1") {
  id
  sale_artwork(cached: false) {
    id
  }
}}
```

and bypass any caching completely.

Also wondering if a memoization option would also be useful, to bypass the loader

**Comment by alloy** [comment]
I’m thinking that instead of adding an option we should maybe never cache sale artworks, if those are the ones that we always run into this problem with.

Any thoughts on this @sweir27 ?

**Comment by alloy** [comment]
For now I’m closing this.
