### ISSUE TITLE
metaphysics monitoring dashboard

### ISSUE THREAD

**Issue by joeyAghion** [artsy/metaphysics#931]
Metaphysics is unstable and doesn't have a clear, single destination for high-level monitoring and metrics. The common course of events is:
* #help requests arrive _or_ alerts start to be triggered in upstream systems (e.g., Force)
* we open Force's heroku metrics
* Depending on that, we tail Force's heroku logs or:
* open Metaphysics' heroku metrics
* tail Metaphysics' heroku logs
* investigate further...

The dashboard should reflect the usual culprits: error rate,  memory, latency.

**Comment by mzikherman** [comment]
Closing as this is addressed by dashboards living in Datadog now that the app is on k8s (https://app.datadoghq.com/screen/302489/metaphysics-production), is linked to in the README, etc.
