### ISSUE TITLE
Metaphysics should specify a user-agent

### ISSUE THREAD

**Issue by joeyAghion** [artsy/metaphysics#937]
API logs show mostly empty user agent values. It would be helpful if Metaphysics identified itself in its requests to the API with the conventional User-Agent header.

**Comment by orta** [comment]
This one is a tad tricky, as MP only makes requests for others, could wrap the existing user agent with it's own e.g. request in `Eigen 4.0; webkit; blah` becomes `Eigen 4.0; webkit; blah; metaphysics`
